version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - bookstoreDb:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: my_pass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: my_pass
      ME_CONFIG_MONGODB_URL: mongodb://admin:my_pass@mongo:27017/

volumes:
  bookstoreDb:
